%%
%  File: Main4_specific_predictions.m
%  Directory: 4_gyujtemegy/11_CCS/2021_COVID19_analizis/study13_SNMPC_LTV_delta
%  Author: Peter Polcz (ppolcz@gmail.com) 
%  
%  Created on 2021. November 09. (2021b)
%


Main0_README
help Main0_README

%%
% Prediction made: 2021.11.09. (november  9, kedd), 14:07
% Prediction from: 2021.11.05. (Friday)
% 

r = pf_param_setup_v2_2021_11_10;
r = pf_load_data(r);

r.Date_Start_MPC = datetime(2020,03,01);
r.Date_End_REC = datetime(2021,07,01);
r.Date_End_PRED = datetime(2021,07,01);
r.Date_Assume_Beta = datetime(2021,11,16);
r.beta_max = 1;
r.beta_jovo = 0.8;
r.V_Naponta_jovo = 3000;

%%

r = mf_epid_tracking_NMPC(r);
% zf_plotter_NMPC(r,...
%     "FigNr",1312, ...
%     "Version","_MPDI_ujsagcikk", ...
%     "Plotter",@(r,args,varargin) zf_latexify_plot_v2(r,args,varargin{:}, ...
%     "Show_Date_Last_Available_Data",false, ...
%     "Show_Date_Start_MPC",false, ...
%     "Show_Months",false));

%%

% r = mf_epid_tracking_SNMPC_init(r);
zf_plotter_MDPI(r, ...
    "FigNr",1, ...
    "Layout",{3,2}, ...
    "Version","_MPDI_ujsagcikk", ...
    "Plotter",@(r,args,varargin) zf_latexify_plot_v2(r,args,varargin{:}, ...
    "Show_Date_Last_Available_Data",false, ...
    "Show_Date_Start_MPC",false, ...
    "Show_Months",false))

zf_plotter_MDPI(r, ...
    "FigNr",2, ...
    "Version","_MPDI_ujsagcikk", ...
    "Plotter",@(r,args,varargin) zf_latexify_plot_v2(r,args,varargin{:}, ...
    "Show_Date_Last_Available_Data",false, ...
    "Show_Date_Start_MPC",false, ...
    "Show_Months",false))

return

%%

r = mf_epid_tracking_SNMPC(r);
zf_plotter_SNMPC(r, ...
    "Layout",{5 2}, ...
    "FigSize",[1053 1306], ...
    "FigNr",8082, ...
    "Version","_after_optimization", ...
    "FigName","After optimization",...
    "Plotter",@(r,args,varargin) zf_latexify_plot_v2(r,args,varargin{:}, ...
    "Show_Date_Last_Available_Data",false, ...
    "Show_Date_Start_MPC",false, ...
    "Show_Months",false))

%%

r.SNMPC_guess

r.SNMPC_sol.x = full(r.SNMPC_sol.x);
r.SNMPC_sol.f = full(r.SNMPC_sol.f);

Relative_difference_f = (r.SNMPC_guess.f - r.SNMPC_sol.f) / r.SNMPC_sol.f

Relative_difference_x = norm(r.SNMPC_guess.x - r.SNMPC_sol.x) / norm(r.SNMPC_sol.x)

%%

tic, r.NMPC_helper.F.Beta_rate.f_J(r.NMPC_sol.x,[]) + r.NMPC_helper.F.H_error.f_J(r.NMPC_sol.x,[]), toc
tic, r.SNMPC_helper.F.Beta_rate.f_J(r.SNMPC_sol.x,[]) + r.SNMPC_helper.F.H_error.f_J(r.SNMPC_sol.x,[]), toc
