%%
%  File: Main4_specific_predictions.m
%  Directory: 4_gyujtemegy/11_CCS/2021_COVID19_analizis/study13_SNMPC_LTV_delta
%  Author: Peter Polcz (ppolcz@gmail.com) 
%  
%  Created on 2021. November 09. (2021b)
%

r = pf_param_setup_v2_2021_11_10;
r = pf_load_data(r);

r.Date_Start_MPC = datetime(2020,03,01);
r.Date_End_REC = datetime(2021,07,01);

%%

r = mf_epid_tracking_NMPC(r);
zf_plotter_NMPC(r,...
    "FigNr",1312, ...
    "Version","_MDPI_manuscript", ...
    "Plotter",@(r,args,varargin) zf_latexify_plot_v2(r,args,varargin{:}, ...
    "Show_Months",false));

%%

r = mf_epid_tracking_SNMPC_init(r);
% r = mf_epid_tracking_SNMPC(r);
zf_plotter_MDPI(r, ...
    "FigNr",1, ...
    "Layout",{3,2}, ...
    "Version","_MDPI_manuscript", ...
    "Plotter",@(r,args,varargin) zf_latexify_plot_v2(r,args,varargin{:}, ...
    "Show_Months",false))

zf_plotter_MDPI(r, ...
    "FigNr",2, ...
    "Version","_MDPI_manuscript", ...
    "Plotter",@(r,args,varargin) zf_latexify_plot_v2(r,args,varargin{:}, ...
    "Show_Months",false))
